cmake_minimum_required(VERSION 3.13)
project( dilation )
find_package( OpenCV REQUIRED )
find_package( OpenMP REQUIRED )
include_directories( ${OpenCV_INCLUDE_DIRS} )
add_executable( deg.out dilation-erosion_grayscale.cpp )
add_executable( de.out  dilation-erosion.cpp           )
add_executable( pde.out p_dilation-erosion.cpp         )
target_link_libraries( deg.out ${OpenCV_LIBS} )
target_link_libraries( de.out ${OpenCV_LIBS}  )
target_link_libraries( pde.out ${OpenCV_LIBS} )
target_link_libraries( pde.out OpenMP::OpenMP_CXX )

